### ISSUE TITLE
Add official support for ESP32

### ISSUE THREAD

**Issue by ciband** [bxparks/AUnit#24]
If you are looking to add support for more boards, please consider ESP32.  If it doesn't work already, it wouldn't take much.

We are using this for our project on ESP32 (see #23)

Thank you.

**Comment by bxparks** [comment]
(Forgot about the auto-close.. Reopening..)

I'll mark this closed when I create a new release.

**Comment by bxparks** [comment]
Released 0.5.1.
Let me know if you run into any issues.
