### ISSUE TITLE
can I use AUnit for Particle projects?

### ISSUE THREAD

**Issue by anderson916** [bxparks/AUnit#48]
Hi, thanks for developing this wonderful tools. I am wondering if I can use it with my particle projects.

For more information, you can visit http://particle.io

Thanks.

**Comment by bxparks** [comment]
I'm not sure... I spend a few minutes looking through the link that you provided, and I can't seem to penetrate the marketing fluff to figure out what the development environment of Particle.io is. It kinda seems to be like Arduino, but I can't whether it's fullly compatible or just a close resemblance. Currently, AUnit is targeted for a C++ environment that's compatible with the Arduino application framework. Is that particle.io?

Maybe you be more specific with your question? Did you encounter specific problems?

**Comment by bxparks** [comment]
Closed due to lack of activity and response...
